### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by LuxusDarkangel** [NorthPL/LogIt#2]
I'm getting a lot of console spam when using this plugin on Cauldron (it occurs when a quarry breaks a block)
Error:
[22:19:32] [Server thread/ERROR]: Could not pass event BlockBreakEvent to LogIt v0.9.0-b12-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1010) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:90) [BlockEvent$BreakEvent.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at buildcraft.factory.BlockMiner.acceptEnergy(BlockMiner.java:94) [BlockMiner.class:?]
	at buildcraft.factory.TileQuarry.dig(TileQuarry.java:233) [TileQuarry.class:?]
	at buildcraft.factory.TileQuarry.func_145845_h(TileQuarry.java:191) [TileQuarry.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2491) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at io.github.lucaseasedup.logit.util.CollectionUtils.containsIgnoreCase(CollectionUtils.java:35) ~[?:?]
	at io.github.lucaseasedup.logit.LogItCore.isPlayerForcedToLogIn(LogItCore.java:962) ~[?:?]
	at io.github.lucaseasedup.logit.listener.BlockEventListener.onBreak(BlockEventListener.java:64) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	... 15 more

**Comment by NorthPL** [comment]
Try to install this version: https://github.com/NorthPL/LogIt/releases/download/0.9.0/logit-0.9.1.jar

**Comment by LuxusDarkangel** [comment]
Yeah, the spam is fixed. Now it shows 2 errors, but that's just one time, it's not spammed, so i don't care about it.
Anyway, here is the log with the errors, fix it if you want and keep up the good work :D
http://pastebin.com/defgZsnh

PD: Offtopic, is there any way to port authme reloaded databases to LogIt?

**Comment by NorthPL** [comment]
When this is shows?

> PD: Offtopic, is there any way to port authme reloaded databases to LogIt?
Type command /logit import authme
(You must have AuthMe folder in /plugins)

**Comment by LuxusDarkangel** [comment]
When the server initializes the plugin,

**Comment by NorthPL** [comment]
Do you have modified values "forceLogin.inWorlds" or "forceLogin.exemptPlayers" in configuration? (if yes, paste it here)

**Comment by LuxusDarkangel** [comment]
Yes, here is my cfg:
http://pastebin.com/PCeCtEWe

The first time i used your plugin, BuildCraft couldn't break blocks, so i used exempt players to add his fake player. After that it worked fine, but now that i've seen the cfg again, it has set [BuildCraft] as - BuildCraft, but it works anyway. I'll try to fix this and let you know if the error is solved.

**Comment by NorthPL** [comment]
It should look like this:
  exemptPlayers:
    - BuildCraft
But, in 0.9.1 it shouldn't be needed.

**Comment by LuxusDarkangel** [comment]
The problem is, fake player nicknames are between [], so it is [BuildCraft], [ComputerCraft], etc..., it should look like - [BuildCraft]. I will try without that option.

**Comment by NorthPL** [comment]
You can also try
```
  exemptPlayers:
   - "[BuildCraft]"
   - "[any other mod]"
```

**Comment by LuxusDarkangel** [comment]
It works fine without exempt players and don't spam anymore, so its ok now.

**Comment by NorthPL** [comment]
This errors not appear? http://pastebin.com/defgZsnh
So... Can I now close this issue?

**Comment by LuxusDarkangel** [comment]
Yup, so i will close this issue.
